export const demoUsers = [
  {
    id: 'user-rahul',
    name: 'Rahul Sharma',
    email: 'rahul.sharma@example.com',
    role: 'Student / Engineering & UPSC Aspirant',
    dob: '2004-05-14',
    fatherName: 'Rajesh Sharma',
    goal: 'Prepare documents for B.Tech Admissions & UPSC Civil Services',
    documents: [
      {
        id: 'doc-aadhaar',
        name: 'Aadhaar Card',
        category: 'Identity',
        status: 'Verified',
        holderName: 'Rahul Sharma',
        dob: '2004-05-14',
        docNumber: 'XXXX-XXXX-8912',
        issuer: 'UIDAI',
        updatedAt: '2026-08-18',
        confidence: 98,
      },
      {
        id: 'doc-pan',
        name: 'PAN Card',
        category: 'Identity',
        status: 'Verified',
        holderName: 'Rahul Sharma',
        dob: '2004-05-14',
        docNumber: 'ABCPS1234F',
        issuer: 'Income Tax Department',
        updatedAt: '2026-08-18',
        confidence: 96,
      },
      {
        id: 'doc-marksheet-10',
        name: '10th Marksheet',
        category: 'Education',
        status: 'Verified',
        holderName: 'Rahul Kumar Sharma',
        dob: '2004-05-14',
        docNumber: 'CBSE-X-892110',
        issuer: 'CBSE Board',
        updatedAt: '2026-08-19',
        confidence: 94,
      },
      {
        id: 'doc-marksheet-12',
        name: '12th Marksheet',
        category: 'Education',
        status: 'Verified',
        holderName: 'Rahul Sharma',
        dob: '2004-05-14',
        docNumber: 'CBSE-XII-901124',
        issuer: 'CBSE Board',
        updatedAt: '2026-08-20',
        confidence: 96,
      },
      {
        id: 'doc-bank-passbook',
        name: 'Bank Passbook',
        category: 'Finance',
        status: 'Needs Review',
        holderName: 'Rahul Sharma',
        dob: '2004-05-14',
        docNumber: 'SBIN0001234',
        issuer: 'State Bank of India',
        updatedAt: '2026-08-20',
        confidence: 72,
      },
    ],
  },
  {
    id: 'user-priya',
    name: 'Priya Patel',
    email: 'priya.patel@example.com',
    role: 'Medical Aspirant (NEET / AIIMS / DY Patil)',
    dob: '2005-11-22',
    fatherName: 'Kirit Patel',
    goal: 'MBBS & Dental Admission Document Verification',
    documents: [
      {
        id: 'doc-priya-aadhaar',
        name: 'Aadhaar Card',
        category: 'Identity',
        status: 'Verified',
        holderName: 'Priya Patel',
        dob: '2005-11-22',
        docNumber: 'XXXX-XXXX-4532',
        issuer: 'UIDAI',
        updatedAt: '2026-08-15',
        confidence: 99,
      },
      {
        id: 'doc-priya-10',
        name: '10th Marksheet',
        category: 'Education',
        status: 'Verified',
        holderName: 'Priya Patel',
        dob: '2005-11-22',
        docNumber: 'GSEB-X-33109',
        issuer: 'Gujarat Secondary Board',
        updatedAt: '2026-08-16',
        confidence: 98,
      },
      {
        id: 'doc-priya-domicile',
        name: 'Domicile Certificate',
        category: 'Revenue & Certificate',
        status: 'Verified',
        holderName: 'Priya Patel',
        dob: '2005-11-22',
        docNumber: 'DOM-GUJ-2026-9',
        issuer: 'Mamlatdar Office',
        updatedAt: '2026-08-17',
        confidence: 92,
      },
    ],
  },
]

export const userProfile = demoUsers[0]

export const colleges = [
  {
    id: 'dr-dy-patil-vidyapeeth',
    name: 'Dr. D. Y. Patil Vidyapeeth (DPU Pune & Navi Mumbai)',
    shortName: 'Dr. D. Y. Patil Vidyapeeth',
    logoIcon: '🏥',
    crestEmoji: '🛡️',
    gradientBadge: 'linear-gradient(135deg, #e11d48, #be123c)',
    badgeColor: '#e11d48',
    location: 'Pimpri, Pune & Navi Mumbai, Maharashtra',
    type: 'Deemed-to-be University (NAAC A++ Accredited)',
    stream: 'Medical (MBBS), Dental, Engineering (B.Tech), Management & Biotechnology',
    ranking: 'NIRF Top 40 / NAAC A++',
    fee: '₹1,50,000 - ₹25,00,000 / year (varies by Medical/Engineering stream)',
    deadline: 'NEET MCC / MHT CET / DPU AIET 2026',
    officialPortal: {
      label: 'DPU Official Admission Portal',
      url: 'https://dpu.edu.in',
    },
    description: 'Premier health sciences, engineering, and biotechnology institute across Pune and Navi Mumbai campuses admitting via NEET UG, MHT-CET, and JEE.',
    requiredDocuments: [
      'NEET UG Scorecard & Admit Card',
      'JEE Main Scorecard',
      '10th Marksheet',
      '12th Marksheet',
      'Aadhaar Card',
      'Transfer Certificate (TC)',
      'Migration Certificate',
      'Domicile',
      'Medical Fitness Certificate',
      'Gap Year Affidavit',
      'Passport Size Photograph',
    ],
    specificNotes: [
      'MBBS and BDS admissions are strictly routed through Directorate General of Health Services (DGHS) / MCC Deemed University Counselling.',
      'Engineering candidates can apply via MHT-CET State Quota or Direct JEE Main All India Seats.',
      'Gap year affidavit on ₹100 stamp paper is mandatory for droppers.',
    ],
  },
  {
    id: 'dr-dy-patil-engg-pune',
    name: 'Dr. D. Y. Patil College of Engineering (DYPCOE Akurdi / Pimpri)',
    shortName: 'DY Patil College of Engineering',
    logoIcon: '⚙️',
    crestEmoji: '🏛️',
    gradientBadge: 'linear-gradient(135deg, #0284c7, #0369a1)',
    badgeColor: '#0284c7',
    location: 'Akurdi & Pimpri, Pune, Maharashtra',
    type: 'Affiliated to Savitribai Phule Pune University (SPPU)',
    stream: 'Engineering & Technology (B.Tech / M.Tech)',
    ranking: 'Top Private Engineering Institute in Pune',
    fee: '₹1,35,000 / year',
    deadline: 'MHT CET CAP Round 1 - July 2026',
    officialPortal: {
      label: 'DYPCOE Engineering Portal',
      url: 'https://www.dypcoeakurdi.ac.in',
    },
    description: 'Top technical institute in Pune famous for Computer Engineering, AI & Data Science, Robotics, and core branches.',
    requiredDocuments: [
      'MHT-CET Scorecard',
      'JEE Main Scorecard',
      '10th Marksheet',
      '12th Marksheet',
      'Aadhaar Card',
      'Transfer Certificate (TC)',
      'Migration Certificate',
      'Domicile',
      'Caste Certificate',
      'Passport Size Photograph',
    ],
    specificNotes: [
      'CAP Allotment letter issued by Maharashtra State CET Cell is mandatory for fee benefit.',
      'Caste Validity certificate is strictly mandatory for Maharashtra backward class reservations.',
    ],
  },
  {
    id: 'coep-pune',
    name: 'COEP Technological University (College of Engineering Pune)',
    shortName: 'COEP Tech University, Pune',
    logoIcon: '🏛️',
    crestEmoji: '📐',
    gradientBadge: 'linear-gradient(135deg, #0d9488, #0f766e)',
    badgeColor: '#0d9488',
    location: 'Shivajinagar, Pune, Maharashtra',
    type: 'State Unitary Technological University (Estd. 1854)',
    stream: 'Engineering & Technology (B.Tech / M.Tech)',
    ranking: 'NIRF Engineering Top 50',
    fee: '₹95,000 / year',
    deadline: 'MHT-CET CAP 2026',
    officialPortal: {
      label: 'COEP Tech Admissions',
      url: 'https://www.coep.org.in',
    },
    description: 'One of the oldest and most prestigious government engineering colleges in Asia.',
    requiredDocuments: [
      'MHT-CET Scorecard',
      '10th Marksheet',
      '12th Marksheet',
      'Aadhaar Card',
      'Domicile',
      'Transfer Certificate (TC)',
      'Migration Certificate',
      'Caste Certificate',
      'Medical Fitness Certificate',
    ],
    specificNotes: [
      'Admission strictly based on MHT-CET 99+ percentile cutoffs through Maharashtra State CET Cell.',
    ],
  },
  {
    id: 'vjti-mumbai',
    name: 'Veermata Jijabai Technological Institute (VJTI Mumbai)',
    shortName: 'VJTI Mumbai',
    logoIcon: '⚡',
    crestEmoji: '⚙️',
    gradientBadge: 'linear-gradient(135deg, #8b5cf6, #7c3aed)',
    badgeColor: '#8b5cf6',
    location: 'Matunga, Mumbai, Maharashtra',
    type: 'Premier Autonomous State Engineering Institute',
    stream: 'Engineering & Technology',
    ranking: 'NIRF Top State Engineering',
    fee: '₹85,000 / year',
    deadline: 'MHT-CET CAP 2026',
    officialPortal: {
      label: 'VJTI Admissions',
      url: 'https://vjti.ac.in',
    },
    description: 'Premier technological institute in Mumbai admitting students with top state ranks.',
    requiredDocuments: [
      'MHT-CET Scorecard',
      '10th Marksheet',
      '12th Marksheet',
      'Aadhaar Card',
      'Domicile',
      'Transfer Certificate (TC)',
      'Migration Certificate',
      'Caste Certificate',
    ],
    specificNotes: [
      'Maharashtra Domicile Certificate (Type A/B/C/D) is mandatory for 85% home state seats.',
    ],
  },
  {
    id: 'iit-bombay',
    name: 'Indian Institute of Technology Bombay (IIT Bombay)',
    shortName: 'IIT Bombay',
    logoIcon: '🏛️',
    crestEmoji: '🛡️',
    gradientBadge: 'linear-gradient(135deg, #0284c7, #0369a1)',
    badgeColor: '#0284c7',
    location: 'Powai, Mumbai, Maharashtra',
    type: 'Institute of National Importance (INI)',
    stream: 'Engineering & Technology',
    ranking: 'NIRF Engineering #1',
    fee: '₹1,15,000 / semester',
    deadline: 'JoSAA Counselling Round 1 - June 2026',
    officialPortal: {
      label: 'JoSAA / IIT Bombay Admissions',
      url: 'https://josaa.nic.in',
    },
    description: 'India’s premier engineering and research institute requiring JoSAA rank allotment.',
    requiredDocuments: [
      'JEE Advanced Scorecard',
      '10th Marksheet',
      '12th Marksheet',
      'Aadhaar Card',
      'Transfer Certificate (TC)',
      'Migration Certificate',
      'Medical Fitness Certificate',
      'Category / EWS Certificate',
      'Anti-Ragging Affidavit',
      'Passport Size Photograph',
    ],
    specificNotes: [
      'Category certificates (OBC-NCL / Gen-EWS) must be in Central Govt format issued on or after April 1, 2026.',
      'Medical certificate must be signed strictly on official JoSAA Annexure 7 format by MBBS Doctor.',
    ],
  },
  {
    id: 'delhi-university',
    name: 'University of Delhi (DU - CSAS Portal)',
    shortName: 'Delhi University (DU)',
    logoIcon: '📚',
    crestEmoji: '🎓',
    gradientBadge: 'linear-gradient(135deg, #8b5cf6, #6d28d9)',
    badgeColor: '#8b5cf6',
    location: 'North & South Campus, New Delhi',
    type: 'Central University',
    stream: 'Arts, Science, Commerce & Management',
    ranking: 'NIRF Top 10 University',
    fee: '₹10,000 - ₹35,000 / year (varies by college)',
    deadline: 'CSAS Phase 1 & 2 - July 2026',
    officialPortal: {
      label: 'DU CSAS Admission Portal',
      url: 'https://ugadmission.uod.ac.in',
    },
    description: 'Centralized admission across 70+ colleges including SRCC, St. Stephens, Hindu College, and Miranda House.',
    requiredDocuments: [
      'CUET Scorecard',
      '10th Marksheet',
      '12th Marksheet',
      'Aadhaar Card',
      'Character Certificate',
      'Migration Certificate',
      'Income Certificate',
      'Caste Certificate',
      'Passport Size Photograph',
    ],
    specificNotes: [
      'Name on CUET Application, 10th Marksheet, and Aadhaar Card must be 100% identical.',
      'Character Certificate should be issued from the institution last attended (valid within 6 months).',
    ],
  },
  {
    id: 'aiims-delhi',
    name: 'All India Institute of Medical Sciences (AIIMS New Delhi)',
    shortName: 'AIIMS Delhi (MBBS)',
    logoIcon: '🏥',
    crestEmoji: '🩺',
    gradientBadge: 'linear-gradient(135deg, #ef4444, #b91c1c)',
    badgeColor: '#ef4444',
    location: 'Ansari Nagar, New Delhi',
    type: 'Autonomous Medical Apex Institute',
    stream: 'Medical & Healthcare (MBBS)',
    ranking: 'NIRF Medical #1',
    fee: '₹1,628 (Complete 5.5-Year MBBS Fee)',
    deadline: 'MCC NEET UG Counselling - August 2026',
    officialPortal: {
      label: 'MCC / AIIMS MBBS Allotment',
      url: 'https://mcc.nic.in',
    },
    description: 'India’s topmost medical institution. Requires rigorous biometric and original document verification.',
    requiredDocuments: [
      'NEET UG Scorecard & Admit Card',
      '10th Marksheet',
      '12th Marksheet',
      'Aadhaar Card',
      'Transfer Certificate (TC)',
      'Migration Certificate',
      'Gap Year Affidavit',
      'Medical Fitness Certificate',
      'Caste Certificate',
      'Passport Size Photograph',
    ],
    specificNotes: [
      'Gap Year Affidavit on ₹10/₹100 stamp paper attested by Notary is mandatory if student took a dropper year.',
      'Physical reporting with original Marksheets is mandatory during Round 1 allotment.',
    ],
  },
  {
    id: 'bits-pilani',
    name: 'Birla Institute of Technology and Science (BITS Pilani)',
    shortName: 'BITS Pilani',
    logoIcon: '🔬',
    crestEmoji: '⚙️',
    gradientBadge: 'linear-gradient(135deg, #059669, #047857)',
    badgeColor: '#059669',
    location: 'Pilani, Rajasthan (Campuses: Goa, Hyd)',
    type: 'Deemed University (Institute of Eminence)',
    stream: 'Engineering & Sciences',
    ranking: 'Top Private Tier-1',
    fee: '₹2,60,000 / semester',
    deadline: 'BITSAT Iterations - July 2026',
    officialPortal: {
      label: 'BITS Admission Portal (BITSAT)',
      url: 'https://www.bitsadmission.com',
    },
    description: 'Merit-based admission purely through BITSAT score with no reservation quotas.',
    requiredDocuments: [
      'BITSAT Scorecard',
      '10th Marksheet',
      '12th Marksheet',
      'Aadhaar Card',
      'Transfer Certificate (TC)',
      'Migration Certificate',
      'Passport Size Photograph',
    ],
    specificNotes: [
      'Aggregate 75% in PCM/PCB in 12th board with minimum 60% in each individual subject is strictly required.',
    ],
  },
  {
    id: 'symbiosis-international',
    name: 'Symbiosis International University (SIU Pune & Lavale)',
    shortName: 'Symbiosis University (SIU)',
    logoIcon: '💼',
    crestEmoji: '🎓',
    gradientBadge: 'linear-gradient(135deg, #d97706, #b45309)',
    badgeColor: '#d97706',
    location: 'Lavale & Viman Nagar, Pune, Maharashtra',
    type: 'Deemed University (Private Tier-1)',
    stream: 'Management (BBA/MBA), Law (SLS), Engineering (SIT) & Media (SIMC)',
    ranking: 'NIRF Top 35 University',
    fee: '₹3,20,000 / year',
    deadline: 'SET / SLAT / SITEEE 2026',
    officialPortal: {
      label: 'Symbiosis Entrance Test (SET)',
      url: 'https://www.set-test.org',
    },
    description: 'Renowned international deemed university famous for Symbiosis Law School (SLS) and SIBM.',
    requiredDocuments: [
      'SET / SLAT / SITEEE Scorecard',
      '10th Marksheet',
      '12th Marksheet',
      'Aadhaar Card',
      'Transfer Certificate (TC)',
      'Migration Certificate',
      'Passport Size Photograph',
    ],
    specificNotes: [
      'Symbiosis Entrance Test scorecard and PI-WAT shortlist letter required for final verification.',
    ],
  },
  {
    id: 'nmims-mumbai',
    name: 'NMIMS Deemed-to-be-University (SVKM’s NMIMS Mumbai)',
    shortName: 'NMIMS Mumbai (NPAT / NMAT)',
    logoIcon: '📊',
    crestEmoji: '💼',
    gradientBadge: 'linear-gradient(135deg, #dc2626, #991b1b)',
    badgeColor: '#dc2626',
    location: 'Vile Parle, Mumbai, Maharashtra',
    type: 'Deemed University (Category 1 Autonomy)',
    stream: 'Commerce (B.Com/BBA), Engineering (MPSTME), Pharmacy & Law',
    ranking: 'NIRF Top 20 Management',
    fee: '₹3,50,000 / year',
    deadline: 'NPAT / NCET 2026',
    officialPortal: {
      label: 'NMIMS NPAT Portal',
      url: 'https://nmims.edu',
    },
    description: 'Premier university in Mumbai offering BBA, B.Com, B.Tech, and MBA programs through NPAT.',
    requiredDocuments: [
      'NPAT / JEE Main Scorecard',
      '10th Marksheet',
      '12th Marksheet',
      'Aadhaar Card',
      'Transfer Certificate (TC)',
      'Migration Certificate',
      'Medical Fitness Certificate',
    ],
    specificNotes: [
      'Minimum 50% in 12th board with Mathematics/Statistics mandatory for BBA/B.Sc Finance.',
    ],
  },
  {
    id: 'mit-wpu-pune',
    name: 'MIT World Peace University (MIT-WPU Kothrud, Pune)',
    shortName: 'MIT-WPU Pune',
    logoIcon: '🕊️',
    crestEmoji: '📐',
    gradientBadge: 'linear-gradient(135deg, #2563eb, #1d4ed8)',
    badgeColor: '#2563eb',
    location: 'Kothrud, Pune, Maharashtra',
    type: 'State Private University',
    stream: 'Engineering, Management, Pharmacy & Liberal Arts',
    ranking: 'Top Private University in Maharashtra',
    fee: '₹3,10,000 / year',
    deadline: 'MIT-WPU UGPET / MHT CET 2026',
    officialPortal: {
      label: 'MIT-WPU Admissions',
      url: 'https://mitwpu.edu.in',
    },
    description: 'Leading multidisciplinary university in Pune offering peace studies, AI, and engineering degrees.',
    requiredDocuments: [
      'MHT-CET / JEE Main Scorecard',
      '10th Marksheet',
      '12th Marksheet',
      'Aadhaar Card',
      'Transfer Certificate (TC)',
      'Migration Certificate',
      'Anti-Ragging Affidavit',
    ],
    specificNotes: [
      'Direct admissions available based on JEE Main / MHT CET percentiles.',
    ],
  },
  {
    id: 'manipal-mahe',
    name: 'Manipal Academy of Higher Education (MAHE Manipal)',
    shortName: 'Manipal University (MIT / KMC)',
    logoIcon: '🏥',
    crestEmoji: '🛡️',
    gradientBadge: 'linear-gradient(135deg, #f59e0b, #d97706)',
    badgeColor: '#f59e0b',
    location: 'Manipal, Karnataka',
    type: 'Institute of Eminence (Deemed University)',
    stream: 'Engineering (MIT), Medical (KMC MBBS), Allied Health & Management',
    ranking: 'NIRF University #6',
    fee: '₹3,35,000 / year (Engineering)',
    deadline: 'MET / NEET 2026',
    officialPortal: {
      label: 'Manipal Admissions Portal',
      url: 'https://manipal.edu',
    },
    description: 'World-class campus offering premier engineering at MIT Manipal and medicine at Kasturba Medical College (KMC).',
    requiredDocuments: [
      'MET / NEET Scorecard',
      '10th Marksheet',
      '12th Marksheet',
      'Aadhaar Card',
      'Transfer Certificate (TC)',
      'Migration Certificate',
      'Medical Fitness Certificate',
    ],
    specificNotes: [
      '50% minimum in PCM/PCB in 12th board required for MET engineering admission.',
    ],
  },
  {
    id: 'thapar-university',
    name: 'Thapar Institute of Engineering and Technology (TIET Patiala)',
    shortName: 'Thapar University, Patiala',
    logoIcon: '🏛️',
    crestEmoji: '⚡',
    gradientBadge: 'linear-gradient(135deg, #10b981, #059669)',
    badgeColor: '#10b981',
    location: 'Patiala, Punjab',
    type: 'Deemed University (NAAC A+)',
    stream: 'Engineering & Computing',
    ranking: 'NIRF Engineering #20',
    fee: '₹2,10,000 / semester',
    deadline: 'TIET Online Portal - June 2026',
    officialPortal: {
      label: 'Thapar Admissions',
      url: 'https://www.thapar.edu',
    },
    description: 'Tier-1 engineering institute offering 50% seats via JEE Main and 50% via 12th Board marks.',
    requiredDocuments: [
      'JEE Main Scorecard',
      '10th Marksheet',
      '12th Marksheet',
      'Aadhaar Card',
      'Transfer Certificate (TC)',
      'Migration Certificate',
      'Character Certificate',
    ],
    specificNotes: [
      'Punjab state quota candidates need Punjab resident certificate for 50% reservation.',
    ],
  },
  {
    id: 'amity-university',
    name: 'Amity University (Noida, Mumbai, Jaipur, Gurugram)',
    shortName: 'Amity University',
    logoIcon: '🎓',
    crestEmoji: '📚',
    gradientBadge: 'linear-gradient(135deg, #6366f1, #4f46e5)',
    badgeColor: '#6366f1',
    location: 'Noida, UP & Mumbai, Maharashtra',
    type: 'Private University (Global Campuses)',
    stream: 'Engineering, Biotechnology, Law, Media & Business',
    ranking: 'Top Private Multidisciplinary University',
    fee: '₹1,50,000 - ₹3,50,000 / year',
    deadline: 'Amity Application 2026',
    officialPortal: {
      label: 'Amity Admission Portal',
      url: 'https://www.amity.edu',
    },
    description: 'Large private university network offering 300+ career streams and direct merit-based entry.',
    requiredDocuments: [
      '10th Marksheet',
      '12th Marksheet',
      'Aadhaar Card',
      'Transfer Certificate (TC)',
      'Migration Certificate',
      'Passport Size Photograph',
    ],
    specificNotes: [
      'Direct admission on 80%+ marks in 12th board without entrance exam.',
    ],
  },
  {
    id: 'chandigarh-university',
    name: 'Chandigarh University (CU Gharuan, Mohali)',
    shortName: 'Chandigarh University (CU)',
    logoIcon: '🏢',
    crestEmoji: '🛡️',
    gradientBadge: 'linear-gradient(135deg, #ef4444, #dc2626)',
    badgeColor: '#ef4444',
    location: 'Mohali, Punjab / Chandigarh NCR',
    type: 'NAAC A+ Accredited Private University',
    stream: 'Engineering, Computer Applications, Aviation & Animation',
    ranking: 'QS Asia Top Ranked Private University',
    fee: '₹1,25,000 / semester',
    deadline: 'CUCET 2026',
    officialPortal: {
      label: 'Chandigarh University CUCET',
      url: 'https://www.cuchd.in',
    },
    description: 'Fast-growing research university with extensive patent filings and campus placements.',
    requiredDocuments: [
      'CUCET Scorecard',
      '10th Marksheet',
      '12th Marksheet',
      'Aadhaar Card',
      'Transfer Certificate (TC)',
      'Migration Certificate',
    ],
    specificNotes: [
      'Scholarships up to 100% available through CUCET entrance examination.',
    ],
  },
]

export const services = [
  {
    id: 'upsc-civil-services',
    title: 'UPSC Civil Services Examination (IAS / IPS / IFS)',
    category: 'Competitive & Civil Services',
    badgeIcon: '🇮🇳',
    badgeColor: '#b45309',
    deadline: 'DAF-1 Submission - August 2026',
    fee: '₹100 (Free for Female/SC/ST/PwD)',
    description: 'Detailed Application Form (DAF) document verification for India’s highest administrative services.',
    officialPortal: {
      label: 'Union Public Service Commission (UPSC)',
      url: 'https://upsconline.nic.in',
    },
    requiredDocuments: [
      '10th Marksheet',
      '12th Marksheet',
      'Graduation Degree / Passing Certificate',
      'Aadhaar Card',
      'Category / EWS Certificate',
      'Disability / PwD Certificate',
      'Passport Size Photograph',
    ],
    steps: [
      'Complete One Time Registration (OTR) on UPSC portal with valid Aadhaar & email.',
      'Upload Matriculation (10th) certificate as absolute proof of Date of Birth.',
      'Submit Graduation Degree Certificate or Bonafide Final Year certificate.',
      'Upload Central Govt format OBC-NCL / EWS / SC / ST caste certificate issued in prescribed financial year.',
    ],
    commonPitfalls: [
      'Spelling differences in candidate name between 10th marksheet and Degree certificate.',
      'OBC-NCL certificate issued after the cutoff date of the preliminary exam notification.',
    ],
  },
  {
    id: 'college-admission',
    title: 'UG / PG Centralized College Admissions 2026',
    category: 'Education & Admissions',
    badgeIcon: '🎓',
    badgeColor: '#0284c7',
    deadline: 'July 31, 2026',
    fee: '₹500 - ₹2,000',
    description: 'Centralized counselling and document verification for university & college admissions.',
    officialPortal: {
      label: 'University Admission / CSAS Portal',
      url: 'https://ugadmission.uod.ac.in',
    },
    requiredDocuments: [
      '10th Marksheet',
      '12th Marksheet',
      'Aadhaar Card',
      'Transfer Certificate (TC)',
      'Migration Certificate',
      'Income Certificate',
      'Domicile',
      'Passport Size Photograph',
    ],
    steps: [
      'Register on the counselling portal with valid email and Aadhaar-linked phone.',
      'Enter 10th & 12th board marks exactly as printed on physical marksheets.',
      'Upload scanned clear copies of marksheets, category/income certificates, and photo.',
      'Lock preferences and proceed with physical document verification at the allotted college.',
    ],
    commonPitfalls: [
      'Spelling differences in candidate name between 10th Marksheet and Aadhaar.',
      'Missing Transfer Certificate (TC) or Migration Certificate from previous school.',
    ],
  },
  {
    id: 'aadhaar-correction',
    title: 'Aadhaar Name / DOB / Address Demographic Update',
    category: 'Government ID & Identity',
    badgeIcon: '🆔',
    badgeColor: '#0d9488',
    deadline: 'No fixed deadline',
    fee: '₹50 online / ₹100 at Kendra',
    description: 'Correct demographic details or update address/name on your official Aadhaar card.',
    officialPortal: {
      label: 'UIDAI myAadhaar Portal',
      url: 'https://myaadhaar.uidai.gov.in',
    },
    requiredDocuments: [
      'Identity Proof',
      'Address Proof',
      'Date of Birth Proof',
      'Aadhaar Card',
    ],
    steps: [
      'Login to myAadhaar portal using your Aadhaar number and OTP.',
      'Select the field to update (Name, DOB, Gender, or Address).',
      'Upload supporting document (10th Marksheet for DOB, Passport/PAN for Name).',
      'Pay online fee of ₹50 and track the URN (Update Request Number).',
    ],
    commonPitfalls: [
      'Uploading blurry or cropped document photos resulting in rejection by UIDAI.',
      'Name changes exceeding 2 lifetime attempts without Gazetted notification.',
    ],
  },
  {
    id: 'post-matric-scholarship',
    title: 'National & State Post-Matric Scholarship (NSP)',
    category: 'Scholarship & Welfare',
    badgeIcon: '💰',
    badgeColor: '#10b981',
    deadline: 'October 15, 2026',
    fee: 'Free of Cost',
    description: 'Financial aid and tuition fee reimbursement for meritorious and category students.',
    officialPortal: {
      label: 'National Scholarship Portal (NSP)',
      url: 'https://scholarships.gov.in',
    },
    requiredDocuments: [
      'Aadhaar Card',
      'Income Certificate',
      'Caste Certificate',
      'Bank Passbook',
      '10th Marksheet',
      '12th Marksheet',
    ],
    steps: [
      'Generate OTR (One Time Registration) using Aadhaar Face Auth or Mobile OTP.',
      'Fill family income details and upload valid Tehsildar-signed Income Certificate.',
      'Link your Bank Account with Aadhaar (NPCI Aadhaar Seeding is mandatory).',
      'Submit the application and download the verification slip for college endorsement.',
    ],
    commonPitfalls: [
      'Bank account is not NPCI-seeded with Aadhaar, causing DBT payment failure.',
      'Income certificate value exceeds the scheme threshold.',
    ],
  },
  {
    id: 'passport-application',
    title: 'Fresh Passport Application (Tatkaal / Normal)',
    category: 'Travel & Identity',
    badgeIcon: '✈️',
    badgeColor: '#3b82f6',
    deadline: 'Appointment Based',
    fee: '₹1,500 (Normal) / ₹3,500 (Tatkaal)',
    description: 'Apply for a fresh 36-page Indian passport via Passport Seva Kendra (PSK).',
    officialPortal: {
      label: 'Passport Seva Portal (Ministry of External Affairs)',
      url: 'https://www.passportindia.gov.in',
    },
    requiredDocuments: [
      'Identity Proof',
      'Address Proof',
      'Date of Birth Proof',
      '10th Marksheet',
      'Aadhaar Card',
    ],
    steps: [
      'Create an account on Passport Seva portal and fill the application form.',
      'Pay appointment fee and schedule visit to nearest PSK or POPSK.',
      'Carry original physical documents along with 2 self-attested photocopies.',
      'Undergo biometric capture at PSK, followed by local Police Verification.',
    ],
    commonPitfalls: [
      'Address proof mismatch between Aadhaar and present living address.',
      'Non-ECR status requires submission of 10th/Higher Education passing certificate.',
    ],
  },
  {
    id: 'pan-aadhaar-link',
    title: 'PAN Card Application & Aadhaar Linkage',
    category: 'Finance & Tax',
    badgeIcon: '💳',
    badgeColor: '#8b5cf6',
    deadline: 'Immediate',
    fee: '₹107 (Physical PAN) / ₹0 (Instant e-PAN)',
    description: 'Apply for a new Permanent Account Number or link PAN with Aadhaar as mandated by IT Dept.',
    officialPortal: {
      label: 'Income Tax e-Filing Portal',
      url: 'https://www.incometax.gov.in',
    },
    requiredDocuments: [
      'Aadhaar Card',
      'Identity Proof',
      'Date of Birth Proof',
      'Passport Size Photograph',
    ],
    steps: [
      'Visit the Income Tax e-filing portal or NSDL/Protean website.',
      'Verify details via Aadhaar e-KYC paperless authentication.',
      'Ensure Full Name, DOB, and Gender match 100% between PAN and Aadhaar records.',
      'Submit request and download digital e-PAN within 10 minutes.',
    ],
    commonPitfalls: [
      'Linking fails if there is even a 1-character typo between PAN and Aadhaar names.',
    ],
  },
]

export const documentEquivalents = {
  'Aadhaar': ['Aadhaar Card', 'Aadhaar', 'UIDAI E-Aadhaar', 'E-Aadhaar'],
  'Aadhaar Card': ['Aadhaar', 'Aadhaar Card', 'UIDAI E-Aadhaar', 'E-Aadhaar'],
  'PAN': ['PAN Card', 'PAN', 'e-PAN'],
  'PAN Card': ['PAN', 'PAN Card', 'e-PAN'],
  '10th Marksheet': ['10th Marksheet', 'Class 10 Marksheet', 'Secondary School Certificate', '10th Passing Certificate', '10th Certificate'],
  '12th Marksheet': ['12th Marksheet', 'Class 12 Marksheet', 'Senior Secondary Certificate', '12th Passing Certificate', '12th Certificate'],
  'Graduation Degree / Passing Certificate': ['Graduation Degree', 'Degree Certificate', 'Provisional Degree', 'Graduation Marksheet'],
  'Identity Proof': ['Aadhaar Card', 'Aadhaar', 'PAN Card', 'PAN', 'Passport', 'Voter ID', 'Driving Licence'],
  'Address Proof': ['Aadhaar Card', 'Aadhaar', 'Passport', 'Voter ID', 'Electricity Bill', 'Bank Passbook'],
  'Date of Birth Proof': ['10th Marksheet', 'Birth Certificate', 'Passport', 'Aadhaar Card'],
  'Income Certificate': ['Income Certificate', 'Tehsildar Income Certificate', 'State e-District Income Certificate'],
  'Domicile': ['Domicile Certificate', 'Domicile', 'Resident Certificate', 'PRC (Permanent Resident Certificate)'],
  'Caste Certificate': ['Caste Certificate', 'SC/ST/OBC Certificate', 'Community Certificate', 'Category / EWS Certificate'],
  'Category / EWS Certificate': ['Caste Certificate', 'Category / EWS Certificate', 'EWS Certificate', 'OBC-NCL Certificate'],
  'Disability / PwD Certificate': ['Disability Certificate', 'PwD Certificate', 'UDID Card'],
  'Bank Passbook': ['Bank Passbook', 'Cancelled Cheque', 'Bank Statement with Seal'],
  'Transfer Certificate (TC)': ['Transfer Certificate (TC)', 'School Leaving Certificate (SLC)', 'College Leaving Certificate (CLC)'],
  'Migration Certificate': ['Migration Certificate', 'Board Migration Certificate', 'University Migration'],
  'Character Certificate': ['Character Certificate', 'Conduct Certificate', 'School Character Certificate'],
  'Gap Year Affidavit': ['Gap Year Affidavit', 'Gap Certificate', 'Gap Affidavit on Stamp Paper'],
  'Medical Fitness Certificate': ['Medical Fitness Certificate', 'Medical Certificate', 'JoSAA Annexure 7'],
  'Anti-Ragging Affidavit': ['Anti-Ragging Affidavit', 'Anti-Ragging Undertaking', 'UGC Anti-Ragging Form'],
  'Passport Size Photograph': ['Passport Size Photo', 'Photo', 'Passport Size Photograph'],
  'JEE Advanced Scorecard': ['JEE Advanced Scorecard', 'JEE Adv Rank Card', 'JEE Advanced / NEET Scorecard'],
  'JEE Main Scorecard': ['JEE Main Scorecard', 'JEE Main Rank Card', 'MHT-CET / JEE Main Scorecard'],
  'MHT-CET Scorecard': ['MHT-CET Scorecard', 'MHT CET Rank Card', 'MHT-CET / JEE Main Scorecard'],
  'NEET UG Scorecard & Admit Card': ['NEET UG Scorecard', 'NEET Scorecard', 'NEET UG Scorecard & Admit Card', 'JEE Advanced / NEET Scorecard', 'MET / NEET Scorecard'],
  'CUET Scorecard': ['CUET Scorecard', 'CUET NTA Scorecard'],
  'BITSAT Scorecard': ['BITSAT Scorecard', 'BITSAT Score Report'],
  'SET / SLAT / SITEEE Scorecard': ['SET / SLAT / SITEEE Scorecard', 'SET Scorecard'],
  'NPAT / JEE Main Scorecard': ['NPAT / JEE Main Scorecard', 'NPAT Scorecard', 'JEE Main Scorecard'],
  'MET / NEET Scorecard': ['MET / NEET Scorecard', 'MET Scorecard', 'NEET UG Scorecard & Admit Card'],
  'CUCET Scorecard': ['CUCET Scorecard', 'CUCET Rank Card'],
  'IPMAT Scorecard & Admit Card': ['IPMAT Scorecard', 'IPMAT Scorecard & Admit Card'],
  'CLAT Scorecard & Admit Card': ['CLAT Scorecard', 'CLAT Rank Card'],
  'Hostel Affidavit': ['Hostel Affidavit', 'Hostel Undertaking'],
  'Community Certificate': ['Community Certificate', 'Caste Certificate'],
}

export const documentGuides = {
  'Aadhaar Card': {
    purpose: 'Primary 12-digit biometric identity & address proof issued by UIDAI.',
    howToGet: 'Download e-Aadhaar from myAadhaar portal (uidai.gov.in) using OTP or visit an Aadhaar Kendra.',
    source: 'UIDAI Portal (uidai.gov.in)',
    priority: 'High',
  },
  'PAN Card': {
    purpose: 'Permanent Account Number for tax identity, banking, and official verification.',
    howToGet: 'Apply via NSDL/Protean or UTIITSL portal for instant e-PAN or physical card.',
    source: 'NSDL / UTIITSL Portal',
    priority: 'High',
  },
  '10th Marksheet': {
    purpose: 'Official proof of basic secondary education and standardized Date of Birth (DOB).',
    howToGet: 'Collect from your school or download digital marksheet from DigiLocker / Board portal.',
    source: 'DigiLocker / Education Board Portal',
    priority: 'High',
  },
  '12th Marksheet': {
    purpose: 'Proof of higher secondary education, stream, subject marks, and qualifying eligibility.',
    howToGet: 'Collect from your school/junior college or fetch digital copy from DigiLocker.',
    source: 'DigiLocker / School or Education Board',
    priority: 'High',
  },
  'Graduation Degree / Passing Certificate': {
    purpose: 'Proof of completed undergraduate degree required for UPSC, CAT, and PG admissions.',
    howToGet: 'Issued by your university registrar or download provisional from university portal.',
    source: 'University Examination Branch',
    priority: 'High',
  },
  'Transfer Certificate (TC)': {
    purpose: 'Proof of officially leaving previous school/college with no dues to join university.',
    howToGet: 'Request from the principal office of your 12th school or previous college.',
    source: 'School/College Administration',
    priority: 'High',
  },
  'Migration Certificate': {
    purpose: 'Mandatory certificate when switching from one education board/university to another.',
    howToGet: 'Issued automatically with 12th board result or apply on board/DigiLocker portal.',
    source: 'CBSE / CISCE / State Board Portal',
    priority: 'High',
  },
  'Character Certificate': {
    purpose: 'Testimonial of student conduct and discipline issued by last attended institution.',
    howToGet: 'Issued by School Principal/College Dean upon completion of 12th board.',
    source: 'School Administration Office',
    priority: 'Medium',
  },
  'Gap Year Affidavit': {
    purpose: 'Legal declaration explaining gap years between 12th and college (e.g. JEE/NEET/MHT-CET prep).',
    howToGet: 'Draft on ₹100 non-judicial stamp paper and get attested by Notary Public.',
    source: 'Local Court / Notary Advocate',
    priority: 'High',
  },
  'Medical Fitness Certificate': {
    purpose: 'Certifies physical and mental fitness to pursue technical/medical education.',
    howToGet: 'Get examined and signed by any MBBS doctor with official medical registration stamp.',
    source: 'Government / Registered Medical Practitioner',
    priority: 'High',
  },
  'Anti-Ragging Affidavit': {
    purpose: 'Mandatory undertaking as per Supreme Court & UGC norms prohibiting ragging.',
    howToGet: 'Fill online free form on antiragging.in or amanmovement.org and submit signed copy.',
    source: 'UGC Anti-Ragging Portal (antiragging.in)',
    priority: 'Medium',
  },
  'Income Certificate': {
    purpose: 'Proof of annual family income required for fee waivers, scholarships, and quotas.',
    howToGet: 'Apply through your state e-District / Revenue department portal or CSC centre.',
    source: 'State Government e-District Portal',
    priority: 'High',
  },
  'Domicile': {
    purpose: 'Proof of permanent residency in a particular state for state-quota seats & schemes.',
    howToGet: 'Apply via State Revenue Department / e-District online portal (e.g. Aaple Sarkar for Maharashtra).',
    source: 'State Citizen Service Portal',
    priority: 'High',
  },
  'Caste Certificate': {
    purpose: 'Proof of SC / ST / OBC / EWS reservation category for quota and relaxation benefits.',
    howToGet: 'Apply through local Tehsildar / Sub-Divisional Magistrate / e-District portal.',
    source: 'District Administration / e-District Portal',
    priority: 'High',
  },
  'Category / EWS Certificate': {
    purpose: 'Central/State format certificate for OBC-NCL, SC, ST, or Gen-EWS quota.',
    howToGet: 'Must be issued by authorized revenue authority on or after April 1 of admission year.',
    source: 'Tehsildar / Sub-Divisional Officer',
    priority: 'High',
  },
  'Disability / PwD Certificate': {
    purpose: 'Proof of benchmark disability issued on Unique Disability ID (UDID) portal.',
    howToGet: 'Apply on swavlambancard.gov.in and undergo medical board verification.',
    source: 'District Hospital / UDID Portal',
    priority: 'High',
  },
  'JEE Advanced Scorecard': {
    purpose: 'Official qualifying scorecard for IIT admissions through JoSAA counselling.',
    howToGet: 'Download scorecard PDF from official JEE Advanced portal (jeeadv.ac.in).',
    source: 'NTA / IIT JEE Adv Portal',
    priority: 'High',
  },
  'JEE Main Scorecard': {
    purpose: 'Scorecard for NITs, IIITs, GFTIs, and state engineering college admissions.',
    howToGet: 'Download NTA score card from jeemain.nta.nic.in.',
    source: 'National Testing Agency (NTA)',
    priority: 'High',
  },
  'MHT-CET Scorecard': {
    purpose: 'Official rank card for engineering and pharmacy admissions across Maharashtra colleges.',
    howToGet: 'Download scorecard from cetcell.mahacet.org.',
    source: 'Maharashtra State CET Cell',
    priority: 'High',
  },
  'NEET UG Scorecard & Admit Card': {
    purpose: 'Rank card for MBBS, BDS, and AYUSH admissions across India.',
    howToGet: 'Download from neet.nta.nic.in.',
    source: 'National Testing Agency (NTA)',
    priority: 'High',
  },
  'CUET Scorecard': {
    purpose: 'Standardized entrance scorecard for Delhi University and 250+ Central/State universities.',
    howToGet: 'Download scorecard from exams.nta.ac.in/CUET-UG.',
    source: 'NTA CUET Portal',
    priority: 'High',
  },
  'BITSAT Scorecard': {
    purpose: 'Official score report for BITS Pilani, Goa, and Hyderabad engineering programs.',
    howToGet: 'Download scorecard from bitsadmission.com.',
    source: 'BITS Admission Portal',
    priority: 'High',
  },
  'Passport Size Photograph': {
    purpose: 'Recent color photograph with white background for physical & digital records.',
    howToGet: 'Take a recent passport photo (3.5cm x 4.5cm) against a plain white background.',
    source: 'Photo Studio / Digital Camera',
    priority: 'Low',
  },
  'Identity Proof': {
    purpose: 'Government-authorized document verifying your legal name, face, and citizenship.',
    howToGet: 'Use Aadhaar, PAN Card, Passport, Voter ID, or Driving Licence.',
    source: 'Authorized Government Issuing Body',
    priority: 'High',
  },
  'Address Proof': {
    purpose: 'Valid proof verifying your current residential address.',
    howToGet: 'Use Aadhaar, Voter ID, Passport, Utility Bill, or Bank Passbook.',
    source: 'Official Service Guidelines',
    priority: 'High',
  },
  'Bank Passbook': {
    purpose: 'Proof of active bank account details (Account number, IFSC, Beneficiary Name).',
    howToGet: 'Get bank passbook stamped from your bank branch or download signed statement.',
    source: 'Your Banking Branch / NetBanking Portal',
    priority: 'Medium',
  },
}

// Function to synthesize college profile for ANY query on the fly
export function synthesizeCollege(query) {
  const cleanName = query.replace(/[^\w\s]/gi, ' ').trim()
  const capitalized = cleanName
    .split(' ')
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join(' ')

  const lower = cleanName.toLowerCase()
  const isMedical = lower.includes('medical') || lower.includes('hospital') || lower.includes('mbbs') || lower.includes('dental') || lower.includes('dpu') || lower.includes('patil')
  const isLaw = lower.includes('law') || lower.includes('legal') || lower.includes('judiciary')
  const isManagement = lower.includes('management') || lower.includes('mba') || lower.includes('bba') || lower.includes('business')

  let stream = 'Engineering, Sciences & Multidisciplinary'
  let exam = 'JEE Main / State CET Scorecard'
  let icon = '🏛️'

  if (isMedical) {
    stream = 'Medical, Dental & Allied Health Sciences (MBBS / BDS)'
    exam = 'NEET UG Scorecard & Admit Card'
    icon = '🏥'
  } else if (isLaw) {
    stream = 'Law & Legal Studies (B.A. LL.B. / LL.M.)'
    exam = 'CLAT / State Law CET Scorecard'
    icon = '⚖️'
  } else if (isManagement) {
    stream = 'Management & Business Administration (BBA / MBA)'
    exam = 'IPMAT / CAT / CMAT Scorecard'
    icon = '💼'
  }

  return {
    id: `dyn-${cleanName.replace(/\s+/g, '-').toLowerCase()}`,
    name: `${capitalized}`,
    shortName: capitalized,
    logoIcon: icon,
    crestEmoji: '🛡️',
    gradientBadge: 'linear-gradient(135deg, #0d9488, #0284c7)',
    badgeColor: '#0d9488',
    location: 'Recognized University Campus (India)',
    type: 'UGC / AICTE / State Registered Higher Education Institution',
    stream,
    ranking: 'Accredited Higher Education Institution (India)',
    fee: 'Standard University Prescribed Fee Structure',
    deadline: 'Academic Year 2026-27 Direct / Counselling Window',
    officialPortal: {
      label: `${capitalized} Official Website`,
      url: `https://www.google.com/search?q=${encodeURIComponent(capitalized + ' official portal admission')}`,
    },
    description: `Auto-verified admission document requirements and prerequisite checklist for ${capitalized}.`,
    requiredDocuments: [
      exam,
      '10th Marksheet',
      '12th Marksheet',
      'Aadhaar Card',
      'Transfer Certificate (TC)',
      'Migration Certificate',
      'Domicile',
      'Income Certificate',
      'Medical Fitness Certificate',
      'Gap Year Affidavit',
      'Passport Size Photograph',
    ],
    specificNotes: [
      'Original 10th marksheet is mandatory for Date of Birth verification.',
      'Candidates taking gap years after 12th must carry a Notary-attested Gap Certificate on stamp paper.',
      'State reservation claims require a valid Category / Caste Validity Certificate.',
    ],
  }
}
